development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:616ec0455545f365ce29c78ce2ba0ed4@sole.redistogo.com:10399/
  # channel_prefix: gearlist_production
